version: '2'
services:
  db:
    image: ursa/postgresql-13.0:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'

  app:
    image: docker.pkg.github.com/ursais/odoo-template/odoo-14:v1.0.0-RC1
    ports:
      - '8069:8069'
      - '8072:8072'
    volumes:
      - 'odoo-data:/odoo/data'
    depends_on:
      - db
    environment:
        - HOST=db
        - USER=odoo
        - PASSWORD=odoo
        - MODE=full
        # - MARABUNTA_FORCE_VERSION=setup

volumes:
  postgres-data:
  odoo-data:
